/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 54HsYifXcmbnw5veKzJ3R2
// Component: VO-JOznlsGEg
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  get as $stateGet,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv
} from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import { usePlasmicInvalidate } from "@plasmicapp/react-web/lib/data-sources";
import { AnimatedStat } from "@/components/AnimatedStat"; // plasmic-import: dmctOjfjQVhJ/codeComponent
import { DonutStatCard } from "@/components/DonutStatCard"; // plasmic-import: SgxQU-TsV9pU/codeComponent
import { DataFetcher } from "@plasmicpkgs/plasmic-query";
import Button from "../../Button"; // plasmic-import: q5yBY-eKZ0QK/component
import { PortBadges } from "@/components/PortBadges"; // plasmic-import: -sOR6cuubXQN/codeComponent
import { Timer } from "@plasmicpkgs/plasmic-basic-components";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 54HsYifXcmbnw5veKzJ3R2/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 54HsYifXcmbnw5veKzJ3R2/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: VO-JOznlsGEg/css
import DatabaseExclamationIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__DatabaseExclamation"; // plasmic-import: Jc4c-GEdYp7J/icon

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array("menu");

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "menuOpened",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "restApi",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return `${window.location.origin}/glances/api/4/`;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return ``;
              }
              throw e;
            }
          })()
      },
      {
        path: "tick",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => 0
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
          onLoad={async event => {
            const $steps = {};
            $steps["updateMenuOpened"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["menuOpened"]
                    },
                    operation: 0
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;
                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateMenuOpened"] != null &&
              typeof $steps["updateMenuOpened"] === "object" &&
              typeof $steps["updateMenuOpened"].then === "function"
            ) {
              $steps["updateMenuOpened"] = await $steps["updateMenuOpened"];
            }
          }}
        >
          <h1
            data-plasmic-name={"h1"}
            data-plasmic-override={overrides.h1}
            className={classNames(
              projectcss.all,
              projectcss.h1,
              projectcss.h1__54HsY,
              projectcss.__wab_text,
              sty.h1
            )}
          >
            {"Lantern"}
          </h1>
          <div className={classNames(projectcss.all, sty.freeBox__yU1Ok)}>
            <div
              className={classNames(
                projectcss.all,
                sty.freeBox__zg5L8,
                "acrylic"
              )}
            >
              <div className={classNames(projectcss.all, sty.freeBox__hUdzK)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b8Z1
                  )}
                >
                  {"CPU"}
                </div>
                <AnimatedStat
                  className={classNames(
                    "__wab_instance",
                    sty.animatedStat__wBcVt
                  )}
                  dataKey={"total"}
                  decimals={1}
                  divisor={1}
                  duration={0.6}
                  endpoint={"cpu"}
                  glancesUrl={(() => {
                    try {
                      return $state.restApi;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  label={``}
                  prefix={""}
                  suffix={"%"}
                  tick={(() => {
                    try {
                      return $state.tick;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return 0;
                      }
                      throw e;
                    }
                  })()}
                />

                <AnimatedStat
                  className={classNames(
                    "__wab_instance",
                    sty.animatedStat___7DdB0
                  )}
                  dataKey={"label:Composite.value"}
                  decimals={1}
                  divisor={1}
                  duration={0.6}
                  endpoint={"sensors"}
                  glancesUrl={(() => {
                    try {
                      return $state.restApi;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  label={``}
                  prefix={""}
                  suffix={"C"}
                  tick={(() => {
                    try {
                      return $state.tick;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return 0;
                      }
                      throw e;
                    }
                  })()}
                />
              </div>
              <DonutStatCard
                className={classNames(
                  "__wab_instance",
                  sty.donutStatCard__ttbd
                )}
                dataKey={"total"}
                duration={0.6}
                emptyColor={"rgba(255,255,255,0.06)"}
                endpoint={"cpu"}
                glancesUrl={(() => {
                  try {
                    return $state.restApi;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                gradientEnd={"#ef4444"}
                gradientMid={"#facc15"}
                gradientStart={"#2dd4bf"}
                innerRadius={30}
                label={``}
                outerRadius={60}
                showValue={false}
                tick={(() => {
                  try {
                    return $state.tick;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return 0;
                    }
                    throw e;
                  }
                })()}
              />
            </div>
            <div
              className={classNames(
                projectcss.all,
                sty.freeBox__hTw1A,
                "acrylic"
              )}
            >
              <div className={classNames(projectcss.all, sty.freeBox__wiDsj)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q4SMx
                  )}
                >
                  {"RAM"}
                </div>
                <AnimatedStat
                  className={classNames(
                    "__wab_instance",
                    sty.animatedStat___9Jv8L
                  )}
                  dataKey={"percent"}
                  decimals={1}
                  divisor={1}
                  duration={0.6}
                  endpoint={"mem"}
                  glancesUrl={(() => {
                    try {
                      return $state.restApi;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  label={``}
                  prefix={""}
                  suffix={"%"}
                  tick={(() => {
                    try {
                      return $state.tick;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return 0;
                      }
                      throw e;
                    }
                  })()}
                />

                <div className={classNames(projectcss.all, sty.freeBox___0SxO)}>
                  <AnimatedStat
                    className={classNames(
                      "__wab_instance",
                      sty.animatedStat__xJuAp
                    )}
                    dataKey={"used"}
                    decimals={1}
                    divisor={1073741824}
                    duration={0.6}
                    endpoint={"mem"}
                    glancesUrl={(() => {
                      try {
                        return $state.restApi;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    label={``}
                    prefix={""}
                    suffix={"GB"}
                    tick={(() => {
                      try {
                        return $state.tick;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return 0;
                        }
                        throw e;
                      }
                    })()}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7JCA
                    )}
                  >
                    {" / "}
                  </div>
                  <AnimatedStat
                    className={classNames(
                      "__wab_instance",
                      sty.animatedStat___8OrGy
                    )}
                    dataKey={"total"}
                    decimals={1}
                    divisor={1073741824}
                    duration={0.6}
                    endpoint={"mem"}
                    glancesUrl={(() => {
                      try {
                        return $state.restApi;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    label={``}
                    prefix={""}
                    suffix={"GB"}
                    tick={(() => {
                      try {
                        return $state.tick;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return 0;
                        }
                        throw e;
                      }
                    })()}
                  />
                </div>
              </div>
              <DonutStatCard
                className={classNames(
                  "__wab_instance",
                  sty.donutStatCard__atIab
                )}
                dataKey={"percent"}
                duration={0.6}
                emptyColor={"rgba(255,255,255,0.06)"}
                endpoint={"mem"}
                glancesUrl={(() => {
                  try {
                    return $state.restApi;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                gradientEnd={"#ef4444"}
                gradientMid={"#facc15"}
                gradientStart={"#2dd4bf"}
                innerRadius={30}
                label={``}
                outerRadius={60}
                showValue={false}
                tick={(() => {
                  try {
                    return $state.tick;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return 0;
                    }
                    throw e;
                  }
                })()}
              />
            </div>
            <div
              className={classNames(
                projectcss.all,
                sty.freeBox___9Ek2M,
                "acrylic"
              )}
            >
              <div className={classNames(projectcss.all, sty.freeBox__q2ERk)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hiOl9
                  )}
                >
                  {"DISK"}
                </div>
                <AnimatedStat
                  className={classNames(
                    "__wab_instance",
                    sty.animatedStat__v1Tg
                  )}
                  dataKey={"percent"}
                  decimals={1}
                  divisor={1}
                  duration={0.6}
                  endpoint={"fs"}
                  glancesUrl={(() => {
                    try {
                      return $state.restApi;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  label={``}
                  prefix={""}
                  suffix={"%"}
                  tick={(() => {
                    try {
                      return $state.tick;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return 0;
                      }
                      throw e;
                    }
                  })()}
                />

                <div className={classNames(projectcss.all, sty.freeBox__lzQg)}>
                  <AnimatedStat
                    className={classNames(
                      "__wab_instance",
                      sty.animatedStat__zf2GE
                    )}
                    dataKey={"used"}
                    decimals={1}
                    divisor={1073741824}
                    duration={0.6}
                    endpoint={"fs"}
                    glancesUrl={(() => {
                      try {
                        return $state.restApi;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    label={``}
                    prefix={""}
                    suffix={"GB"}
                    tick={(() => {
                      try {
                        return $state.tick;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return 0;
                        }
                        throw e;
                      }
                    })()}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oMuyp
                    )}
                  >
                    {" / "}
                  </div>
                  <AnimatedStat
                    className={classNames(
                      "__wab_instance",
                      sty.animatedStat__z0O0N
                    )}
                    dataKey={"size"}
                    decimals={1}
                    divisor={1073741824}
                    duration={0.6}
                    endpoint={"fs"}
                    glancesUrl={(() => {
                      try {
                        return $state.restApi;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    label={``}
                    prefix={""}
                    suffix={"GB"}
                    tick={(() => {
                      try {
                        return $state.tick;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return 0;
                        }
                        throw e;
                      }
                    })()}
                  />
                </div>
              </div>
              <DonutStatCard
                className={classNames(
                  "__wab_instance",
                  sty.donutStatCard__tGq2Z
                )}
                dataKey={"percent"}
                duration={0.6}
                emptyColor={"rgba(255,255,255,0.06)"}
                endpoint={"fs"}
                glancesUrl={(() => {
                  try {
                    return $state.restApi;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                gradientEnd={"#ef4444"}
                gradientMid={"#facc15"}
                gradientStart={"#2dd4bf"}
                innerRadius={30}
                label={``}
                outerRadius={60}
                showValue={false}
                tick={(() => {
                  try {
                    return $state.tick;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return 0;
                    }
                    throw e;
                  }
                })()}
              />
            </div>
          </div>
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__qczhu,
              "acrylic"
            )}
          >
            <div className={classNames(projectcss.all, sty.freeBox___2L1M9)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gYthh
                )}
              >
                {"Containers"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__z8Ww
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return undefined;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "5 running \u00b7 1 stopped";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            </div>
            <DataFetcher
              data-plasmic-name={"httpRestApiFetcher"}
              data-plasmic-override={overrides.httpRestApiFetcher}
              className={classNames("__wab_instance", sty.httpRestApiFetcher)}
              dataName={"fetchedData"}
              errorDisplay={
                <DataCtxReader__>
                  {$ctx => (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wGDxX)}
                    >
                      <DatabaseExclamationIcon
                        data-plasmic-name={"svg"}
                        data-plasmic-override={overrides.svg}
                        className={classNames(projectcss.all, sty.svg)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__o8CzR
                        )}
                      >
                        {
                          "Error fetching data, make sure Lantern has access to the docker socket"
                        }
                      </div>
                    </div>
                  )}
                </DataCtxReader__>
              }
              errorName={"fetchError"}
              loadingDisplay={
                <DataCtxReader__>{$ctx => "Loading..."}</DataCtxReader__>
              }
              method={"GET"}
              noLayout={false}
              previewErrorDisplay={false}
              url={(() => {
                try {
                  return $state.restApi + "containers";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
            >
              <DataCtxReader__>
                {$ctx =>
                  (_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                    (() => {
                      try {
                        return $ctx.fetchedData.sort((a, b) =>
                          a.name.localeCompare(b.name)
                        );
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
                  ).map((__plasmic_item_0, __plasmic_idx_0) => {
                    const currentItem = __plasmic_item_0;
                    const currentIndex = __plasmic_idx_0;
                    return (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kq0G
                        )}
                        key={currentIndex}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__s77Bm
                          )}
                        >
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__wLd9S
                            )}
                            color={(() => {
                              try {
                                return currentItem.status === "restarting"
                                  ? "warning"
                                  : currentItem.status === "stopped"
                                    ? "danger"
                                    : "success";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return [];
                                }
                                throw e;
                              }
                            })()}
                            label={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___5Wyie
                                )}
                              >
                                {""}
                              </div>
                            }
                            roundedFull={true}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jsq3X
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return currentItem.name;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "jellyfin";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                          <AnimatedStat
                            className={classNames(
                              "__wab_instance",
                              sty.animatedStat__zbVFd
                            )}
                            dataKey={``}
                            decimals={1}
                            divisor={1}
                            duration={0.6}
                            endpoint={``}
                            glancesUrl={undefined}
                            label={``}
                            prefix={""}
                            staticValue={currentItem.cpu.total}
                            suffix={"% CPU"}
                            tick={(() => {
                              try {
                                return $state.tick;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return 0;
                                }
                                throw e;
                              }
                            })()}
                          />

                          <AnimatedStat
                            className={classNames(
                              "__wab_instance",
                              sty.animatedStat__ul594
                            )}
                            dataKey={``}
                            decimals={1}
                            divisor={1073741824}
                            duration={0.6}
                            endpoint={``}
                            glancesUrl={undefined}
                            label={``}
                            prefix={""}
                            staticValue={currentItem.memory.usage}
                            suffix={"GB"}
                            tick={(() => {
                              try {
                                return $state.tick;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return 0;
                                }
                                throw e;
                              }
                            })()}
                          />

                          <PortBadges
                            data-plasmic-name={"portBadges"}
                            data-plasmic-override={overrides.portBadges}
                            className={classNames(
                              "__wab_instance",
                              sty.portBadges
                            )}
                            ports={(() => {
                              try {
                                return currentItem.ports;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          >
                            <DataCtxReader__>
                              {$ctx =>
                                (_par =>
                                  !_par
                                    ? []
                                    : Array.isArray(_par)
                                      ? _par
                                      : [_par])(
                                  (() => {
                                    try {
                                      return $ctx.ports;
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return [];
                                      }
                                      throw e;
                                    }
                                  })()
                                ).map((__plasmic_item_1, __plasmic_idx_1) => {
                                  const currentItem = __plasmic_item_1;
                                  const currentIndex = __plasmic_idx_1;
                                  return (
                                    <button
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.button,
                                        projectcss.button__54HsY,
                                        projectcss.__wab_text,
                                        sty.button__iNsy5,
                                        ``
                                      )}
                                      key={currentIndex}
                                      onClick={async event => {
                                        const $steps = {};
                                        $steps["goToPage"] = true
                                          ? (() => {
                                              const actionArgs = {
                                                destination: (() => {
                                                  try {
                                                    return (
                                                      window.location.origin +
                                                      ":" +
                                                      currentItem.host
                                                    );
                                                  } catch (e) {
                                                    if (
                                                      e instanceof TypeError ||
                                                      e?.plasmicType ===
                                                        "PlasmicUndefinedDataError"
                                                    ) {
                                                      return "";
                                                    }
                                                    throw e;
                                                  }
                                                })()
                                              };
                                              return (({ destination }) => {
                                                if (
                                                  typeof destination ===
                                                    "string" &&
                                                  destination.startsWith("#")
                                                ) {
                                                  document
                                                    .getElementById(
                                                      destination.substr(1)
                                                    )
                                                    .scrollIntoView({
                                                      behavior: "smooth"
                                                    });
                                                } else {
                                                  location.assign(destination);
                                                }
                                              })?.apply(null, [actionArgs]);
                                            })()
                                          : undefined;
                                        if (
                                          $steps["goToPage"] != null &&
                                          typeof $steps["goToPage"] ===
                                            "object" &&
                                          typeof $steps["goToPage"].then ===
                                            "function"
                                        ) {
                                          $steps["goToPage"] =
                                            await $steps["goToPage"];
                                        }
                                      }}
                                    >
                                      <React.Fragment>
                                        {currentItem.host +
                                          "/" +
                                          currentItem.protocol}
                                      </React.Fragment>
                                    </button>
                                  );
                                })
                              }
                            </DataCtxReader__>
                          </PortBadges>
                        </div>
                      </div>
                    );
                  })
                }
              </DataCtxReader__>
            </DataFetcher>
          </div>
          <Timer
            data-plasmic-name={"timer"}
            data-plasmic-override={overrides.timer}
            className={classNames("__wab_instance", sty.timer)}
            intervalSeconds={2}
            isRunning={true}
            onTick={async () => {
              const $steps = {};
              $steps["refreshData"] = true
                ? (() => {
                    const actionArgs = {
                      queryInvalidation: ["plasmic_refresh_all"]
                    };
                    return (async ({ queryInvalidation }) => {
                      if (!queryInvalidation) {
                        return;
                      }
                      await plasmicInvalidate(queryInvalidation);
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["refreshData"] != null &&
                typeof $steps["refreshData"] === "object" &&
                typeof $steps["refreshData"].then === "function"
              ) {
                $steps["refreshData"] = await $steps["refreshData"];
              }
              $steps["updateTick"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["tick"]
                      },
                      operation: 2
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;
                      const oldValue = $stateGet(objRoot, variablePath);
                      $stateSet(objRoot, variablePath, oldValue + 1);
                      return oldValue + 1;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateTick"] != null &&
                typeof $steps["updateTick"] === "object" &&
                typeof $steps["updateTick"].then === "function"
              ) {
                $steps["updateTick"] = await $steps["updateTick"];
              }
            }}
            runWhileEditing={false}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "h1", "httpRestApiFetcher", "svg", "portBadges", "timer"],
  h1: ["h1"],
  httpRestApiFetcher: ["httpRestApiFetcher", "svg", "portBadges"],
  svg: ["svg"],
  portBadges: ["portBadges"],
  timer: ["timer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    httpRestApiFetcher: makeNodeComponent("httpRestApiFetcher"),
    svg: makeNodeComponent("svg"),
    portBadges: makeNodeComponent("portBadges"),
    timer: makeNodeComponent("timer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
