/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 54HsYifXcmbnw5veKzJ3R2
// Component: VO-JOznlsGEg
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv
} from "@plasmicapp/react-web/lib/host";
import { StatsProvider } from "@/components/StatsProvider"; // plasmic-import: 1usApmODc_nZ/codeComponent
import { AnimatedStat } from "@/components/AnimatedStat"; // plasmic-import: dmctOjfjQVhJ/codeComponent
import { DonutStatCard } from "@/components/DonutStatCard"; // plasmic-import: SgxQU-TsV9pU/codeComponent
import Button from "../../Button"; // plasmic-import: q5yBY-eKZ0QK/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 54HsYifXcmbnw5veKzJ3R2/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 54HsYifXcmbnw5veKzJ3R2/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: VO-JOznlsGEg/css

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array("menu");

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <h1
            data-plasmic-name={"h1"}
            data-plasmic-override={overrides.h1}
            className={classNames(
              projectcss.all,
              projectcss.h1,
              projectcss.h1__54HsY,
              projectcss.__wab_text,
              sty.h1
            )}
          >
            {"Lantern \ud83c\udfee"}
          </h1>
          <StatsProvider
            data-plasmic-name={"statsProvider"}
            data-plasmic-override={overrides.statsProvider}
            className={classNames("__wab_instance", sty.statsProvider)}
          >
            <DataCtxReader__>
              {$ctx => (
                <React.Fragment>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jom5R)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__usGyN,
                        "acrylic"
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vDrK
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uomiW
                          )}
                        >
                          {"CPU"}
                        </div>
                        <AnimatedStat
                          className={classNames(
                            "__wab_instance",
                            sty.animatedStat___3HdYn
                          )}
                          decimals={1}
                          divisor={1}
                          duration={0.3}
                          label={``}
                          prefix={""}
                          suffix={"%"}
                          value={(() => {
                            try {
                              return $ctx.stats.cpu.percent;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return 0;
                              }
                              throw e;
                            }
                          })()}
                        />

                        <AnimatedStat
                          className={classNames(
                            "__wab_instance",
                            sty.animatedStat__rbHgf
                          )}
                          decimals={1}
                          divisor={1}
                          duration={0.3}
                          label={``}
                          prefix={""}
                          suffix={"C"}
                          value={(() => {
                            try {
                              return $ctx.stats.cpu.temp;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return 0;
                              }
                              throw e;
                            }
                          })()}
                        />
                      </div>
                      <DonutStatCard
                        className={classNames(
                          "__wab_instance",
                          sty.donutStatCard__pYs8
                        )}
                        duration={0.6}
                        emptyColor={"rgba(255,255,255,0.06)"}
                        gradientEnd={"#ef4444"}
                        gradientMid={"#facc15"}
                        gradientStart={"#2dd4bf"}
                        innerRadius={30}
                        label={``}
                        outerRadius={60}
                        showValue={false}
                        value={(() => {
                          try {
                            return $ctx.stats.cpu.percent;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return 0;
                            }
                            throw e;
                          }
                        })()}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__opn8U,
                        "acrylic"
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___48Put
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___65Q9K
                          )}
                        >
                          {"RAM"}
                        </div>
                        <AnimatedStat
                          className={classNames(
                            "__wab_instance",
                            sty.animatedStat__lKAie
                          )}
                          decimals={1}
                          divisor={1}
                          duration={0.3}
                          label={``}
                          prefix={""}
                          suffix={"%"}
                          value={(() => {
                            try {
                              return $ctx.stats.mem.percent;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return 0;
                              }
                              throw e;
                            }
                          })()}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__zZHr
                          )}
                        >
                          <AnimatedStat
                            className={classNames(
                              "__wab_instance",
                              sty.animatedStat__cesa4
                            )}
                            decimals={1}
                            divisor={1}
                            duration={0.3}
                            label={``}
                            prefix={""}
                            suffix={"GB"}
                            value={(() => {
                              try {
                                return $ctx.stats.mem.used;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return 0;
                                }
                                throw e;
                              }
                            })()}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__u2Xin
                            )}
                          >
                            {" / "}
                          </div>
                          <AnimatedStat
                            className={classNames(
                              "__wab_instance",
                              sty.animatedStat___4Tb1K
                            )}
                            decimals={1}
                            divisor={1}
                            duration={0.3}
                            label={``}
                            prefix={""}
                            suffix={"GB"}
                            value={(() => {
                              try {
                                return $ctx.stats.mem.total;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return 0;
                                }
                                throw e;
                              }
                            })()}
                          />
                        </div>
                      </div>
                      <DonutStatCard
                        className={classNames(
                          "__wab_instance",
                          sty.donutStatCard__fa0Q5
                        )}
                        duration={0.6}
                        emptyColor={"rgba(255,255,255,0.06)"}
                        gradientEnd={"#ef4444"}
                        gradientMid={"#facc15"}
                        gradientStart={"#2dd4bf"}
                        innerRadius={30}
                        label={``}
                        outerRadius={60}
                        showValue={false}
                        value={(() => {
                          try {
                            return $ctx.stats.mem.percent;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return 0;
                            }
                            throw e;
                          }
                        })()}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__ixzq,
                        "acrylic"
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__arfB2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mKdxg
                          )}
                        >
                          {"DISK"}
                        </div>
                        <AnimatedStat
                          className={classNames(
                            "__wab_instance",
                            sty.animatedStat__qUnYc
                          )}
                          decimals={1}
                          divisor={1}
                          duration={0.6}
                          label={``}
                          prefix={""}
                          suffix={"%"}
                          value={(() => {
                            try {
                              return $ctx.stats.disk.percent;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return 0;
                              }
                              throw e;
                            }
                          })()}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wy0BG
                          )}
                        >
                          <AnimatedStat
                            className={classNames(
                              "__wab_instance",
                              sty.animatedStat__o7Q5Y
                            )}
                            decimals={1}
                            divisor={1}
                            duration={0.3}
                            label={``}
                            prefix={""}
                            suffix={"GB"}
                            value={(() => {
                              try {
                                return $ctx.stats.disk.used;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return 0;
                                }
                                throw e;
                              }
                            })()}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___8YTh
                            )}
                          >
                            {" / "}
                          </div>
                          <AnimatedStat
                            className={classNames(
                              "__wab_instance",
                              sty.animatedStat__dc1Ta
                            )}
                            decimals={1}
                            divisor={1}
                            duration={0.3}
                            label={``}
                            prefix={""}
                            suffix={"GB"}
                            value={(() => {
                              try {
                                return $ctx.stats.disk.total;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return 0;
                                }
                                throw e;
                              }
                            })()}
                          />
                        </div>
                      </div>
                      <DonutStatCard
                        className={classNames(
                          "__wab_instance",
                          sty.donutStatCard__nzHaY
                        )}
                        duration={0.3}
                        emptyColor={"rgba(255,255,255,0.06)"}
                        gradientEnd={"#ef4444"}
                        gradientMid={"#facc15"}
                        gradientStart={"#2dd4bf"}
                        innerRadius={30}
                        label={``}
                        outerRadius={60}
                        showValue={false}
                        value={(() => {
                          try {
                            return $ctx.stats.disk.percent;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return 0;
                            }
                            throw e;
                          }
                        })()}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      sty.freeBox___2Z3S4,
                      "acrylic"
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__po51B)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hn90N
                        )}
                      >
                        {"Containers"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jkAhv
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return undefined;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "5 running \u00b7 1 stopped";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    {(_par =>
                      !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                      (() => {
                        try {
                          return $ctx.stats.containers;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [];
                          }
                          throw e;
                        }
                      })()
                    ).map((__plasmic_item_0, __plasmic_idx_0) => {
                      const currentItem = __plasmic_item_0;
                      const currentIndex = __plasmic_idx_0;
                      return (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cad36
                          )}
                          key={currentIndex}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___0QvRp
                            )}
                          >
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__ieEP
                              )}
                              color={(() => {
                                try {
                                  return currentItem.status === "restarting"
                                    ? "warning"
                                    : currentItem.status === "stopped"
                                      ? "danger"
                                      : "success";
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()}
                              label={
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__oZjW
                                  )}
                                >
                                  {""}
                                </div>
                              }
                              roundedFull={true}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xtEFe
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return currentItem.name;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "jellyfin";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <AnimatedStat
                              className={classNames(
                                "__wab_instance",
                                sty.animatedStat__b5Rh
                              )}
                              decimals={1}
                              divisor={1}
                              duration={0.3}
                              label={``}
                              prefix={""}
                              suffix={"% CPU"}
                              value={(() => {
                                try {
                                  return currentItem.cpu;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return 0;
                                  }
                                  throw e;
                                }
                              })()}
                            />

                            <AnimatedStat
                              className={classNames(
                                "__wab_instance",
                                sty.animatedStat__rr32K
                              )}
                              decimals={1}
                              divisor={1}
                              duration={0.3}
                              label={``}
                              prefix={""}
                              suffix={"GB"}
                              value={(() => {
                                try {
                                  return currentItem.mem_gb;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return 0;
                                  }
                                  throw e;
                                }
                              })()}
                            />

                            {(_par =>
                              !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                              (() => {
                                try {
                                  return currentItem.ports;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()
                            ).map((__plasmic_item_1, __plasmic_idx_1) => {
                              const currentItem = __plasmic_item_1;
                              const currentIndex = __plasmic_idx_1;
                              return (
                                <button
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.button,
                                    projectcss.button__54HsY,
                                    projectcss.__wab_text,
                                    sty.button__b8Ak7,
                                    ``
                                  )}
                                  key={currentIndex}
                                  onClick={async event => {
                                    const $steps = {};
                                    $steps["goToPage"] = true
                                      ? (() => {
                                          const actionArgs = {
                                            destination: (() => {
                                              try {
                                                const port =
                                                  typeof currentItem ===
                                                  "string"
                                                    ? currentItem.split("/")[0]
                                                    : currentItem?.host;
                                                return (
                                                  window.location.protocol +
                                                  "//" +
                                                  window.location.hostname +
                                                  ":" +
                                                  port
                                                );
                                              } catch (e) {
                                                if (
                                                  e instanceof TypeError ||
                                                  e?.plasmicType ===
                                                    "PlasmicUndefinedDataError"
                                                ) {
                                                  return "";
                                                }
                                                throw e;
                                              }
                                            })()
                                          };
                                          return (({ destination }) => {
                                            if (
                                              typeof destination === "string" &&
                                              destination.startsWith("#")
                                            ) {
                                              document
                                                .getElementById(
                                                  destination.substr(1)
                                                )
                                                .scrollIntoView({
                                                  behavior: "smooth"
                                                });
                                            } else {
                                              location.assign(destination);
                                            }
                                          })?.apply(null, [actionArgs]);
                                        })()
                                      : undefined;
                                    if (
                                      $steps["goToPage"] != null &&
                                      typeof $steps["goToPage"] === "object" &&
                                      typeof $steps["goToPage"].then ===
                                        "function"
                                    ) {
                                      $steps["goToPage"] =
                                        await $steps["goToPage"];
                                    }
                                  }}
                                >
                                  <React.Fragment>{currentItem}</React.Fragment>
                                </button>
                              );
                            })}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </React.Fragment>
              )}
            </DataCtxReader__>
          </StatsProvider>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "h1", "statsProvider"],
  h1: ["h1"],
  statsProvider: ["statsProvider"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    statsProvider: makeNodeComponent("statsProvider"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
